### ISSUE TITLE
Need to write backend

### ISSUE THREAD

**Issue by calebsander** [olynch/commie-qotw#1]

**Comment by olynch** [comment]
Do you have a skype? I'm around today for API spec discussion.

**Comment by calebsander** [comment]
I think I put most of it in the Google Doc you sent out, but my Skype is "clebsander".

**Comment by calebsander** [comment]
I can't seem to run your code; I get:

```
java.io.FileNotFoundException: Could not locate commie_qotw/auth__init.class or commie_qotw/auth.clj
```

**Comment by olynch** [comment]
Yeah, yeah, yeah, it's a bit of a work in progress

**Comment by olynch** [comment]
I've allocated the next two weeks to coding projects and music theory, so this will be worked on.
